# Generated by Django 5.2.6 on 2026-01-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='static/uploads/'),
        ),
    ]
