# Generated by Django 5.2.6 on 2026-01-09 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_slug'),
        ('userspage', '0002_alter_cart_unique_together_alter_cart_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash On Delivery'), ('Esewa', 'Esewa')], max_length=50)),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
